name: puc_app
description: A Flutter app for buying utility tokens from different municipalities.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_inappwebview: ^6.1.5
  get: ^4.6.6
  loading_animation_widget: ^1.3.0
  json_annotation: ^4.9.0
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^6.1.0
  tutorial_coach_mark: ^1.2.12
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.3
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  dio: ^5.3.3
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  lottie: ^3.3.1
  confetti: ^0.8.0
  uuid: ^4.5.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  rename_app: ^1.6.1
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.4
  change_app_package_name: ^1.4.0
  test: ^1.24.3
  http: ^1.2.2


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: HostGrotesk
      fonts:
        - asset: assets/fonts/HostGrotesk-Regular.ttf
        - asset: assets/fonts/HostGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/HostGrotesk-Italic.ttf
          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
